# Game Configurations
FIELD_ROW = 15
FIELD_COL = 15
BARRICADE_COVERAGE = 0.4
HARD_BARRICADE_COVERAGE = 0.2
BARRICADE_HP_RANGE = (50, 200)
BARRICADE_ARMOR_RANGE = (1, 3)
SOUND_REDUCTION = 2
HEAT_REDUCTION = 1
